### ISSUE TITLE
error Received malformed response from registry for "safepay-react-native". The registry may be down.

### ISSUE THREAD

**Issue by Avais392** [getsafepay/safepay-react-native-sdk#5]
While installing the package through 
yarn add safepay-react-native

I am getting this error

error Received malformed response from registry for "safepay-react-native". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by ziyadparekh** [comment]
Apolgies - the package has been published now and the Readme has been updated to reflect new installation commands

[@sfpy/react-native-sdk](https://www.npmjs.com/package/@sfpy/react-native-sdk)
