### ISSUE TITLE
info There appears to be trouble with your network connection. Retrying... error Received malformed response from registry for "safepay-react-native-sdk". The registry may be down. info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### ISSUE THREAD

**Issue by Avais392** [getsafepay/safepay-react-native-sdk#6]
While installing the package through
yarn add safepay-react-native

I am getting this error, even though my internet connection is pretty stable

info There appears to be trouble with your network connection. Retrying...
error Received malformed response from registry for "safepay-react-native-sdk". The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by ziyadparekh** [comment]
Apolgies - the package has been published now and the Readme has been updated to reflect new installation commands

[@sfpy/react-native-sdk](https://www.npmjs.com/package/@sfpy/react-native-sdk)
